VERSION = "1.1.0.0"
COMPANY_NAME = "DGP-Studio"
FILE_DESCRIPTION = "A network Diagnosis tool for DGP-Studio Snap Hutao project"
INTERNAL_NAME = "Snap Hutao Network Diagnosis Tool"
COPYRIGHT = "Masterain"
PRODUCT_NAME = "SH-Network-Diagnosis-Tool.exe"
